Some pylint cleanups for gramps/gen/plug/*.py
gramps-project/gramps pull request #1503
Opened 2023-08-09 01:54 UTC by cdhorn

2024-04-16 16:35 UTC, Nick-Hall requested changes
Only a few things to check on this one.

Our policy is not to include pylint comment statements in the code.

2024-04-16 16:35 UTC, Nick-Hall commented on gramps/gen/plug/_manager.py
> +                        print("   Plugin '{plugin.id}' requires: {plugin.depends_on}")
Should this be an f-string?

2024-04-16 16:35 UTC, Nick-Hall commented on gramps/gen/plug/_manager.py
> +                        print("Plugin '{plugin.name}' did not run; continuing...")
Another f-string?

2024-04-16 16:35 UTC, Nick-Hall commented on gramps/gen/plug/_options.py
> +                        for _, data in enumerate(module_docgen_opts[docgen_name]):
Can we remove the `enumerate` here if the index is not needed?

2024-04-25 00:55 UTC, cdhorn commented
@Nick-Hall this should be ready now.

2024-05-04 15:41 UTC, Nick-Hall approved these changes

2024-05-04 18:26 UTC, merged