latex treedoc: convert images to thumbnails for embedding
gramps-project/gramps pull request #1620
Opened 2023-11-18 21:43 UTC by azrdev

Images are included by the latex code in full into the rendering, instead of only the rectangle selected in gramps' media DB. Having lots of big photos with small faces in my setup, this leads to unreasonably huge PDF files with unrecognizably small faces in them.

Also, some characters (e.g. comma, spaces) in filepaths might trouble the latex parser, see 75921ceaf and 2da93aad1 -- using thumbnails this is circumvented.

However, note this makes the resulting .tex file not standalone anymore.

2023-11-18 21:44 UTC, azrdev commented
Already tried to submit the patch to the mailinglist for discussion, but the attachment was stripped.

2025-01-08 23:19 UTC, Nick-Hall commented
Rebased.

2025-01-09 00:04 UTC, Nick-Hall commented
This PR is causing unit tests to fail.

2025-01-09 11:29 UTC, dsblank requested changes
Move import

2025-01-09 11:29 UTC, dsblank commented on gramps/gen/plug/docgen/treedoc.py
> +from ...utils.thumbnails import get_thumbnail_path
Move import to `def write_node()`

```suggestion
```

2025-01-14 19:16 UTC, Nick-Hall commented on gramps/gen/plug/docgen/treedoc.py
> +from ...utils.thumbnails import get_thumbnail_path
I've moved the import.

2025-01-14 19:28 UTC, merged

2025-07-03 21:00 UTC, hgohel commented
@azrdev Is there an enhancement issue associated with this change? This has caused regression [bug 13888](https://gramps-project.org/bugs/view.php?id=13888).

2025-08-08 01:02 UTC, giotodibondone commented
Yes restore the previous behavior and make this pr as an option or the other way around please!

2025-08-11 15:17 UTC, azrdev commented
> @azrdev Is there an enhancement issue associated with this change? This sounds like a helpful enhancement, but it has caused regression [bug 13888](https://gramps-project.org/bugs/view.php?id=13888).

I think if there was an issue, I'd have linked it here and in the commit message