Installing 5.1.x after 5.2.x will no longer override config/data locations
gramps-project/gramps pull request #1708
Opened 2024-04-18 10:42 UTC by hgohel

Fix #13261

In an existing 5.2.x installation with XDG directory layout for data/config/cache, installing 5.1.x later would create a second config folder in the legacy layout, overriding the existing config.

This change makes it so that if an existing configuration exists for 5.2.x, it will be given preference over the 5.1.x config. If there isn't one, previous logic will continue to be used.

Testing passed on Windows
1. Gramps 5.2.2 only
2. Gramps 5.2.2 followed by Gramps 5.1.6

Could use testing on Linux and MacOS platforms. Thanks!

2024-04-18 12:19 UTC, hgohel commented on gramps/gen/const.py
> +if os.path.exists(USER_DATA) and os.path.exists(USER_CONFIG):
This condition could be merged into elif later on but readability/understandability is lost, so I left it this way with a pass statement.

2024-04-23 03:28 UTC, jralls commented
macOS, at least in the AIO bundle, isn't affected by the bug and this change is harmless.

2024-04-27 09:18 UTC, hgohel commented
> macOS, at least in the AIO bundle, isn't affected by the bug and this change is harmless.

Thanks for reviewing the change.

2024-05-04 14:45 UTC, Nick-Hall requested changes
This works on Linux, but the `GRAMPSHOME` and `SAFEMODE` options are ignored if the new directory structure exists.

The `GRAMPSHOME` environment variable is used to specify a base directory for all data and configuration file storage.  The safe mode works by setting this to an empty directory.

2024-05-27 20:20 UTC, hgohel commented
@Nick-Hall Returning to this defect after a while. Discovered a related bug while trying out safe mode, which affects the testing of this one so I think it needs to be fixed first: [13300](https://gramps-project.org/bugs/view.php?id=13300). It would be very convenient if the root cause of that turns out to be the same as this one.

2024-05-31 01:22 UTC, hgohel commented
@Nick-Hall Turns out that this defect is a side-effect of [13300](https://gramps-project.org/bugs/view.php?id=13300), and the fix for that is in PR #1726 (gramps52) and PR #1725 (master). I'm closing this PR in favor of those.

2024-05-31 01:22 UTC, closed without merging